movie_project/movie_app/urls.py
from django.urls import path, include
from .import views
app_name='movie_app'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    Name=models.CharField(max_length=250)
    Description=models.TextField()
    Year=models.IntegerField()
    Image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.Name

movie_project/movie_app/forms.py
from django import forms

from movie_app.models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['Name','Description','Year','Image']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movie_app.forms import MovieForm
from movie_app.models import Movie


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    #return HttpResponse("This is movie no. %s"%movie_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('Name')
        desc=request.POST.get('Description')
        year=request.POST.get('Year')
        img=request.FILES['Image']
        movie=Movie(Name=name,Description=desc,Year=year,Image=img)
        movie.save()
        return redirect('/')

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" style="width: 400px;background-color: #E5E8E8; " name="Name" placeholder=" Enter the movie name"><br>
  <input type="text" style="height: 300px;width: 400px;background-color: #E5E8E8;" name="Description" placeholder=" Enter the movie Description"><br>
  <input type="text" style="width: 400px;background-color: #E5E8E8;" name="Year" placeholder=" Release Date"><br>
  <input type="file" name="Image" ><br>
  <input type="submit"><br>

</form>
{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <title>Title</title>
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
<!--    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    <h5>Online Movie Store</h5>
  </a>
    <a class="btn btn-primary" href="{% url 'movie_app:add_movie' %}">Add</a>
</nav>
{% block body%}
{% endblock %}

</body>
</html>

movie_project/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h1>Do you want to delete ? </h1>
  <input type="submit">
</form>
{% endblock %}

movie_project/templates/details.html
{% extends 'base.html' %}
{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
          <img src="{{movie.Image.url}}" width='700' height='900'>
        </div>
        <div class="col-md-6">

            <h1>{{movie.Name}}<br><br></h1>
            {{movie.Description}}<br><br>
            {{movie.Year}}<br><br>
             <a class="btn btn-warning" href = "{% url 'movie_app:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href = "{% url 'movie_app:delete' movie.id %}">Delete</a>
        </div>
    </div>

</div>


{% endblock %}

movie_project/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body%}
<div class="container-fluid">
    <div class="row">
        {% for i in movie_list%}
        <div class="col-md-3">
            <div class="card" style="width:350;height=2000;">
                <img class="card-img-top" src="{{i.Image.url}}" alt="Card image cap" width="400px" height="300px">
                <div class="card-body">
                    <h5 class="card-title">{{i.Name}}</h5>
                    <p class="card-text" >{{i.Year}}</p>
                    <a href="{% url 'movie_app:details' i.id%}" class="btn btn-primary">{{i.Name}}</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}